services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    port: 5000  # Render will map this to the port specified in the PORT environment variable
